# Generated by Django 2.2.4 on 2019-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_data',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='imglink',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=850),
        ),
    ]
